<?php
declare(strict_types=1);
return [
'zh'=>[
'title'=>'Yikai 数据库','subtitle'=>'管理本地网站的数据','site'=>'当前网站','ready'=>'连接正常','offline'=>'数据库尚未就绪','start'=>'请先在桌面面板启动环境。','database'=>'数据库','tables'=>'数据表','backup'=>'备份数据库','backup_desc'=>'保存一份完整备份到本机，也可以下载。','restore'=>'恢复数据库','restore_desc'=>'选择备份文件，将内容恢复到当前数据库。','browse'=>'查看数据','browse_desc'=>'浏览数据表、搜索和修改记录。','sql'=>'执行 SQL','sql_desc'=>'打开 SQL 编辑器，运行自己的查询。','advanced'=>'高级管理','recent'=>'最近的备份','empty'=>'还没有备份','download'=>'下载','create'=>'立即备份','choose'=>'选择文件','import'=>'开始恢复','confirm'=>'恢复会修改当前数据库，确定继续？','busy'=>'正在处理，请稍候…','done'=>'操作完成','failed'=>'操作失败','name'=>'数据表','rows'=>'记录数（估算）','open'=>'打开','no_tables'=>'数据库已就绪，还没有数据表。可以先安装网站。','size'=>'大小','back'=>'返回数据库首页','connection'=>'连接信息','credentials'=>'本机默认账号','saved'=>'备份已保存','restored'=>'恢复完成','file_required'=>'请选择备份文件。','invalid_file'=>'备份文件格式不正确。','missing'=>'没有找到数据库，请先启动环境。','error'=>'暂时无法连接','note'=>'MySQL 使用 SQL 文件，SQLite 使用数据库文件。','language'=>'语言','refresh'=>'刷新','restore_hint'=>'MySQL：.sql；SQLite：.sqlite / .db','csrf'=>'页面已过期，请刷新后重试。','large'=>'文件超过上传限制，请选择小于 128 MB 的备份。','operation'=>'数据库操作','backup_first'=>'恢复前建议先保存一份当前备份。'
],
'en'=>[
'title'=>'Yikai Database','subtitle'=>'Manage your local website data','site'=>'Website','ready'=>'Connected','offline'=>'Database is not ready','start'=>'Start the environment in the desktop panel first.','database'=>'Database','tables'=>'Tables','backup'=>'Back up database','backup_desc'=>'Save a complete local backup or download it.','restore'=>'Restore database','restore_desc'=>'Choose a backup to restore into this database.','browse'=>'Browse data','browse_desc'=>'Explore tables, search and edit records.','sql'=>'Run SQL','sql_desc'=>'Open the SQL editor and run a query.','advanced'=>'Advanced manager','recent'=>'Recent backups','empty'=>'No backups yet','download'=>'Download','create'=>'Back up now','choose'=>'Choose file','import'=>'Restore now','confirm'=>'Restoring will change this database. Continue?','busy'=>'Working, please wait…','done'=>'Completed','failed'=>'Operation failed','name'=>'Table','rows'=>'Rows (estimated)','open'=>'Open','no_tables'=>'The database is ready but has no tables. Install the website first.','size'=>'Size','back'=>'Back to database home','connection'=>'Connection details','credentials'=>'Local default account','saved'=>'Backup saved','restored'=>'Restore completed','file_required'=>'Choose a backup file.','invalid_file'=>'Invalid backup file format.','missing'=>'Database not found. Start the environment first.','error'=>'Unable to connect','note'=>'MySQL uses SQL files. SQLite uses database files.','language'=>'Language','refresh'=>'Refresh','restore_hint'=>'MySQL: .sql; SQLite: .sqlite / .db','csrf'=>'Page expired. Refresh and retry.','large'=>'The file exceeds the upload limit. Choose a backup smaller than 128 MB.','operation'=>'Database operation','backup_first'=>'Save a current backup before restoring.'
],
'ja'=>[
'title'=>'Yikai データベース','subtitle'=>'ローカルサイトのデータを管理','site'=>'サイト','ready'=>'接続済み','offline'=>'データベースの準備ができていません','start'=>'先にデスクトップパネルで環境を起動してください。','database'=>'データベース','tables'=>'テーブル','backup'=>'バックアップ','backup_desc'=>'完全なバックアップを保存・ダウンロードします。','restore'=>'データベースの復元','restore_desc'=>'バックアップを選び、現在のデータベースへ復元します。','browse'=>'データを見る','browse_desc'=>'テーブルの閲覧、検索、レコードの編集。','sql'=>'SQL を実行','sql_desc'=>'SQL エディターでクエリを実行します。','advanced'=>'詳細管理','recent'=>'最近のバックアップ','empty'=>'バックアップはまだありません','download'=>'ダウンロード','create'=>'今すぐ保存','choose'=>'ファイルを選択','import'=>'復元を開始','confirm'=>'現在のデータベースが変更されます。続行しますか？','busy'=>'処理中です。しばらくお待ちください…','done'=>'完了しました','failed'=>'操作に失敗しました','name'=>'テーブル','rows'=>'行数（概算）','open'=>'開く','no_tables'=>'接続できましたが、テーブルはありません。サイトをインストールしてください。','size'=>'サイズ','back'=>'データベースのホームへ','connection'=>'接続情報','credentials'=>'ローカルの既定アカウント','saved'=>'バックアップを保存しました','restored'=>'復元が完了しました','file_required'=>'バックアップを選択してください。','invalid_file'=>'バックアップの形式が正しくありません。','missing'=>'データベースがありません。環境を起動してください。','error'=>'接続できません','note'=>'MySQL は SQL ファイル、SQLite はデータベースファイルを使用します。','language'=>'言語','refresh'=>'更新','restore_hint'=>'MySQL：.sql、SQLite：.sqlite / .db','csrf'=>'ページの有効期限が切れました。再読み込みしてください。','large'=>'128 MB 未満のバックアップを選択してください。','operation'=>'データベース操作','backup_first'=>'復元前に現在のバックアップを保存してください。'
],
];
